### ISSUE TITLE
htsjdk.samtools.SAMException: Unable to find entry for contig: rCRS

### ISSUE THREAD

**Issue by Jiafeng-Li-leon** [seppinho/mutserve#33]
Hi, i got some porblems like below when i use the mutserve .
"htsjdk.samtools.SAMException: Unable to find entry for contig: rCRS"
My bam was mapped to the rCRS,but also get that error.
What should i do to solve that?
Looking forward to your reply!

**Comment by seppinho** [comment]
Using this file https://raw.githubusercontent.com/seppinho/mutserve/master/files/rCRS.fasta should do the trick. Important: The latest version set BAQ to false so it should also work with your reference
