### ISSUE TITLE
line break in raw.txt file

### ISSUE THREAD

**Issue by haansi** [seppinho/mutserve#39]
in rc6 -> --write-raw emits wrong file - no newline after last entry per sample after position 16569:

S5.bam  16569   G       G       -       G       -       2617    2908    5525    0       0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0     1.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     []S20.bam       1       G       G       -       G       -       1088    1361    2449    0       0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0     1.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     []
S20.bam 2       A       A       G       A       -       1128    1364    2492    0       0.0     0.999113475177305       0.0     8.865248226950354E-4    0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.999113475177305       1.0     8.865248226950354E-4    0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     []

**Comment by seppinho** [comment]
fixed
